# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cve/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cve/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.contracts.gRPC.cve.v1 import message_pb2 as cve_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ve/v1/service.proto\x12\x06\x63ve.v1\x1a\x14\x63ve/v1/message.proto2\x86\x03\n\x12\x43VEServiceServicer\x12\x44\n\x0bRegisterCVE\x12\x19.cve.v1.AddEntriesRequest\x1a\x1a.cve.v1.AddEntriesResponse\x12=\n\x08ListCVEs\x12\x17.cve.v1.ListCVEsRequest\x1a\x18.cve.v1.ListCVEsResponse\x12L\n\rGetCheckpoint\x12\x1c.cve.v1.GetCheckpointRequest\x1a\x1d.cve.v1.GetCheckpointResponse\x12L\n\rSetCheckpoint\x12\x1c.cve.v1.SetCheckpointRequest\x1a\x1d.cve.v1.SetCheckpointResponse\x12O\n\x0eUpsertCPEBatch\x12\x1d.cve.v1.UpsertCPEBatchRequest\x1a\x1e.cve.v1.UpsertCPEBatchResponse2^\n\x14\x43VECollectorServicer\x12\x46\n\x0b\x43ollectCVEs\x12\x1a.cve.v1.CollectCVEsRequest\x1a\x1b.cve.v1.CollectCVEsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cve.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CVESERVICESERVICER']._serialized_start=55
  _globals['_CVESERVICESERVICER']._serialized_end=445
  _globals['_CVECOLLECTORSERVICER']._serialized_start=447
  _globals['_CVECOLLECTORSERVICER']._serialized_end=541
# @@protoc_insertion_point(module_scope)
