# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.contracts.gRPC.cve.v1 import message_pb2 as cve_dot_v1_dot_message__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cve/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CVEServiceServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCVE = channel.unary_unary(
                '/cve.v1.CVEServiceServicer/RegisterCVE',
                request_serializer=cve_dot_v1_dot_message__pb2.AddEntriesRequest.SerializeToString,
                response_deserializer=cve_dot_v1_dot_message__pb2.AddEntriesResponse.FromString,
                _registered_method=True)
        self.ListCVEs = channel.unary_unary(
                '/cve.v1.CVEServiceServicer/ListCVEs',
                request_serializer=cve_dot_v1_dot_message__pb2.ListCVEsRequest.SerializeToString,
                response_deserializer=cve_dot_v1_dot_message__pb2.ListCVEsResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/cve.v1.CVEServiceServicer/GetCheckpoint',
                request_serializer=cve_dot_v1_dot_message__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=cve_dot_v1_dot_message__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.SetCheckpoint = channel.unary_unary(
                '/cve.v1.CVEServiceServicer/SetCheckpoint',
                request_serializer=cve_dot_v1_dot_message__pb2.SetCheckpointRequest.SerializeToString,
                response_deserializer=cve_dot_v1_dot_message__pb2.SetCheckpointResponse.FromString,
                _registered_method=True)
        self.UpsertCPEBatch = channel.unary_unary(
                '/cve.v1.CVEServiceServicer/UpsertCPEBatch',
                request_serializer=cve_dot_v1_dot_message__pb2.UpsertCPEBatchRequest.SerializeToString,
                response_deserializer=cve_dot_v1_dot_message__pb2.UpsertCPEBatchResponse.FromString,
                _registered_method=True)


class CVEServiceServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterCVE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCVEs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertCPEBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CVEServiceServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCVE': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCVE,
                    request_deserializer=cve_dot_v1_dot_message__pb2.AddEntriesRequest.FromString,
                    response_serializer=cve_dot_v1_dot_message__pb2.AddEntriesResponse.SerializeToString,
            ),
            'ListCVEs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCVEs,
                    request_deserializer=cve_dot_v1_dot_message__pb2.ListCVEsRequest.FromString,
                    response_serializer=cve_dot_v1_dot_message__pb2.ListCVEsResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=cve_dot_v1_dot_message__pb2.GetCheckpointRequest.FromString,
                    response_serializer=cve_dot_v1_dot_message__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'SetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCheckpoint,
                    request_deserializer=cve_dot_v1_dot_message__pb2.SetCheckpointRequest.FromString,
                    response_serializer=cve_dot_v1_dot_message__pb2.SetCheckpointResponse.SerializeToString,
            ),
            'UpsertCPEBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertCPEBatch,
                    request_deserializer=cve_dot_v1_dot_message__pb2.UpsertCPEBatchRequest.FromString,
                    response_serializer=cve_dot_v1_dot_message__pb2.UpsertCPEBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cve.v1.CVEServiceServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cve.v1.CVEServiceServicer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CVEServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterCVE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cve.v1.CVEServiceServicer/RegisterCVE',
            cve_dot_v1_dot_message__pb2.AddEntriesRequest.SerializeToString,
            cve_dot_v1_dot_message__pb2.AddEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCVEs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cve.v1.CVEServiceServicer/ListCVEs',
            cve_dot_v1_dot_message__pb2.ListCVEsRequest.SerializeToString,
            cve_dot_v1_dot_message__pb2.ListCVEsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cve.v1.CVEServiceServicer/GetCheckpoint',
            cve_dot_v1_dot_message__pb2.GetCheckpointRequest.SerializeToString,
            cve_dot_v1_dot_message__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cve.v1.CVEServiceServicer/SetCheckpoint',
            cve_dot_v1_dot_message__pb2.SetCheckpointRequest.SerializeToString,
            cve_dot_v1_dot_message__pb2.SetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertCPEBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cve.v1.CVEServiceServicer/UpsertCPEBatch',
            cve_dot_v1_dot_message__pb2.UpsertCPEBatchRequest.SerializeToString,
            cve_dot_v1_dot_message__pb2.UpsertCPEBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CVECollectorServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectCVEs = channel.unary_unary(
                '/cve.v1.CVECollectorServicer/CollectCVEs',
                request_serializer=cve_dot_v1_dot_message__pb2.CollectCVEsRequest.SerializeToString,
                response_deserializer=cve_dot_v1_dot_message__pb2.CollectCVEsResponse.FromString,
                _registered_method=True)


class CVECollectorServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollectCVEs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CVECollectorServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectCVEs': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectCVEs,
                    request_deserializer=cve_dot_v1_dot_message__pb2.CollectCVEsRequest.FromString,
                    response_serializer=cve_dot_v1_dot_message__pb2.CollectCVEsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cve.v1.CVECollectorServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cve.v1.CVECollectorServicer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CVECollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectCVEs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cve.v1.CVECollectorServicer/CollectCVEs',
            cve_dot_v1_dot_message__pb2.CollectCVEsRequest.SerializeToString,
            cve_dot_v1_dot_message__pb2.CollectCVEsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
